# deploy to astro
name: Deploy DAG to Astro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy DAG to Astro
        uses: astronomer/deploy-action@v1 
        with:
          astro-api-token: ${{ secrets.ASTRO_API_TOKEN }}
          workspace-id: ${{ secrets.ASTRO_WORKSPACE_ID }}
          deployment-id: ${{ secrets.ASTRO_DEPLOYMENT_ID }}
